language: java
sudo: false

jdk:
   - openjdk8

# cache
cache: false

# install
before_install:
# For permission denied in travis-ci
   - chmod +x gradlew

install: skip

# build
script:
   - ./gradlew clean build --no-daemon --console plain

# notifications
notifications:
   email:
      recipients:
         - 18829346477@163.com
         - 1421793864@qq.com
         - suyang2678@qq.com
         - 706044772@qq.com
      on_success: change
      on_failure: always
      on_cancel: never
      on_error: never
      on_start: never

after_success:
   - ./gradlew cleanAll
