server:
   port: 80

pss:
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
      formatSql: true
      show-sql: true
