create table Employee (
       id integer generated by default as identity,
        account varchar(255),
        name varchar(255),
        password varchar(255),
        branch_id integer,
        department_id integer,
        primary key (id)
    )


