server:
   port: 80

# Hibernate config
pss:
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
#      session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
      formatSql: true
      show-sql: true

