server:
   port: 80

# Cache Config
spring:
   cache:
      ehcache:
         config: classpath:ehcache.xml
      type: ehcache

# Hibernate config
pss:
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
#      session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
      formatSql: true
      show-sql: true
